# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

spatial_hetero_perm <- function(x, uv, poly = 2L, resample = 5000L, bw = 10, kernel = 0L, verbose = 0L) {
    .Call(`_hgwrr_spatial_hetero_perm`, x, uv, poly, resample, bw, kernel, verbose)
}

hgwr_bfml <- function(g, x, z, y, u, group, bw, bw_optim, kernel, alpha, eps_iter, eps_gradient, max_iters, max_retries, ml_type, verbose) {
    .Call(`_hgwrr_hgwr_bfml`, g, x, z, y, u, group, bw, bw_optim, kernel, alpha, eps_iter, eps_gradient, max_iters, max_retries, ml_type, verbose)
}

