# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.hgwr_bml <- function(
    g, x, z, y, u, group, bw, kernel,
    alpha, eps_iter, eps_gradient,
    max_iters, max_retries,
    ml_type, verbose
) {
    kernel_index <- switch(
        kernel,
        "gaussian" = 0L,
        "bisquared" = 1L
    )
    .Call(
        `_hgwrr_backfitting_maximum_likelihood`,
        g, x, z, y, u, group, bw, kernel_index,
        alpha, eps_iter, eps_gradient,
        max_iters, max_retries,
        ml_type, verbose
    )
}
